
spring:
  datasource:
    url: jdbc:hsqldb:mem:dbtest
    username: root
    password: 123456
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/jpa-bug-demo.log
  level:
    root: info
